version: "3.3"
services:
    bot:
        image: "sharipavoni/gitlab-discord-bot:1"
        ports:
            - "0.0.0.0.:8000:3000"
        volumes:
            - ./.env:/app/.env
            - ./users.json:/app/users.json
            - ./titles.json:/app/titles.json
